//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultation()
        {
            this.ConsultationsDiagnosis = new HashSet<ConsultationsDiagnosi>();
            this.ConsultationsOtherServices = new HashSet<ConsultationsOtherService>();
            this.LabResults = new HashSet<LabResult>();
            this.PatientsRecords = new HashSet<PatientsRecord>();
            this.PrescribedMedications = new HashSet<PrescribedMedication>();
        }
    
        public System.Guid Id { get; set; }
        public string AspNetUserId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationsDiagnosi> ConsultationsDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationsOtherService> ConsultationsOtherServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabResult> LabResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientsRecord> PatientsRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescribedMedication> PrescribedMedications { get; set; }
    }
}
