//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public System.Guid Id { get; set; }
        public string MedicineName { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Dosage { get; set; }
        public System.Guid DrugCatergoryId { get; set; }
    
        public virtual DrugsCategory DrugsCategory { get; set; }
    }
}
