//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescribedMedication
    {
        public System.Guid Id { get; set; }
        public System.Guid ConsultationId { get; set; }
        public string Medication { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Consultation Consultation { get; set; }
    }
}
