//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityLog
    {
        public System.Guid Id { get; set; }
        public string AspNetUserId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.Guid> SubUserId { get; set; }
        public string SubUserIdentity { get; set; }
        public string JobDescription { get; set; }
        public string TableModified { get; set; }
        public string FormAccessed_ { get; set; }
        public System.Guid FileGUID { get; set; }
    }
}
