//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubUsersInRole
    {
        public System.Guid Id { get; set; }
        public System.Guid SubUserId { get; set; }
        public System.Guid RolesId { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SubUserRole SubUserRole { get; set; }
        public virtual SubUser SubUser { get; set; }
    }
}
